# We are targeting RISC-V AND Xtensa - we use the esp toolchain since it supports both.

[toolchain]
targets = ["riscv32imac-unknown-none-elf","riscv32imc-unknown-none-elf","xtensa-esp32-none-elf","xtensa-esp32s2-none-elf","xtensa-esp32s3-none-elf"]
channel = "esp"
